### PR TITLE
docs: add 'How to Test' subsection to PR template

### PR DESCRIPTION
**Pull request by joelpalmer**
- [x] The title of the PR is formatted according to the semantic commit guidelines

## What is the current behavior?

There is no "How to Test" section

## What is the new behavior?

There is a "How to Test" section

I find that on most PRs it is helpful to code reviewers and new team members to have this information. 

On countless occasions, I've seen the process of authors going back and adding this section result in finding many bugs. This is a great quality control.

More often that not, I ask authors to back and add this section. Having it in the template will save time all around. 

When we start using GitHub template forms #1, this section could be optional or have N/A as a choice _if_ we want. 

## Other Information

Please indicate any change in wording you'd like in your review. My goal is to get the subsection in and make it clear that _**manual**_ testing instructions go in it. Anything else can be changed if you think it is better. I don't want to overthink it though. 😄 
  

**Does this PR introduce a breaking change?** 

No

### CODE REVIEW

**Review by tlebel — APPROVED** [review]
This is truly an amazing idea! 🤩

I also noticed a real positive difference in PR quality / review time spent when a thoughtful demo/instructions was shared by the author.

**Review by Bamblehorse — APPROVED** [review]
Good idea - reminds me of the `How to demo` section on Lilypad feature issues - but in reverse from a technical standpoint 🔄 🙂

**Comment by joelpalmer** [comment]
@Ignigena even though we usually go with 2 approvals, this is somewhat policy related, crosses teams and is not benign. So, wanted your sign-off as well.

**Comment by Ignigena** [comment]
Yeah good to keep this short and sweet. The _intention_ originally was to always have a How to Demo with each task that would also serve as acceptance criteria and "how to test" as you've described it here. But I think encouraging folks to elaborate on that in their PR is good and makes the PR process faster.

Just want to make sure this does not _replace_ the How to Demo. Tasks should still be scoped with that whenever possible so that we can compare the _current_ state of the proposed solution with the _original_ requirements and prompt conversation if we need to when a requirement is missed.

Only feedback is to add the `<!--` comment tags around that block since it's not intended to be visible. This way the instructions don't have to be deleted every time. Ideally we keep things to one line here and link to the team docs for anything more verbose -- otherwise it becomes noise that your brain filters out once you know the pattern.

```
<!-- ✍️ Describe how to _manually_ test the new behavior -->
<!-- 📄 https://maxsystems.github.io/team/#/contributing/PR -->
```

But given that we'll be migrating all of these [templates over to issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), I'm not going to bike shed this too much 😆

**Comment by joelpalmer** [comment]
> Yeah good to keep this short and sweet. The _intention_ originally was to always have a How to Demo with each task that would also serve as acceptance criteria and "how to test" as you've described it here. But I think encouraging folks to elaborate on that in their PR is good and makes the PR process faster.
> 
> Just want to make sure this does not _replace_ the How to Demo. Tasks should still be scoped with that whenever possible so that we can compare the _current_ state of the proposed solution with the _original_ requirements and prompt conversation if we need to when a requirement is missed.
> 
> Only feedback is to add the `<!--` comment tags around that block since it's not intended to be visible. This way the instructions don't have to be deleted every time. Ideally we keep things to one line here and link to the team docs for anything more verbose -- otherwise it becomes noise that your brain filters out once you know the pattern.
> 
> ```
> 
> 
> ```
> 
> But given that we'll be migrating all of these [templates over to issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), I'm not going to bike shed this too much 😆

Works for me. I think the one line is enough. I just really wanted to get _manual_ in there. 😄 

Over in **How to Demo**, the steps are visible and intended to be erased. So, I went off that. Yea absolutely **How to Demo** is not going anywhere. This is for elaborating in their PR.

**Comment by joelpalmer** [comment]
@Ignigena updated for your approval.

**Review by Ignigena — APPROVED** [review]

**Pull request merged**
